package com.example.demo.controllers;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.example.demo.entity.Trainer;
import com.example.demo.repository.TrainerRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/Trainer") // This means URL's start with /demo (after Application path)
public class ControllerTrainer {
	@Autowired // This means to get the bean called corsiRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private TrainerRepository trainerRepository;

	@PostMapping(path = "/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser(@RequestParam String anagrafica, @RequestParam String email,
			@RequestParam String nomeUtente, @RequestParam String password, @RequestParam String numTelefono,
			@RequestParam String info) {
		

		return "Saved";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Trainer> getAllPalestre() {
		// This returns a JSON or XML with the users
		return trainerRepository.findAll();
	}

}
